### ISSUE TITLE
Optimize deployment task scaling rules

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/OpenPedCan-api#31]
Set deployment task scaling rules to optimize runtime and cost, according to load testing results in #27 .

cc @chinwallaa @taylordm @afarrel

**Comment by blackdenc** [comment]
This is going to take re-writing how we use autoscaling rules in kids-first/aws-infra-ecs-service-type-1-module to use network traffic instead of memory because of how R processes reserve memory. 

Given the size of this change, and that this solution should be temporary until FNL implements their own solution, I'm going to recommend that we increase the task count instead of make this change per our convo from Monday's catchup

**Comment by logstar** [comment]
> This is going to take re-writing how we use autoscaling rules in kids-first/aws-infra-ecs-service-type-1-module to use network traffic instead of memory because of how R processes reserve memory.
> 
> Given the size of this change, and that this solution should be temporary until FNL implements their own solution, I'm going to recommend that we increase the task count instead of make this change per our convo from Monday's catchup

@blackdenc - Thank you. I agree.
