### ISSUE TITLE
Update TPM boxplots to show relapse tumors side-by-side with primary tumors

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/OpenPedCan-api#51]
Currently, `/tpm/gene-disease-gtex` and `/tpm/gene-all-cancer` boxplots only show primary tumors.

As suggested by @taylordm , the TPM boxplots could be updated to show relapse tumors side-by-side with primary tumors. Primary tumors and relapse tumors could be plotted with different box colors, and a legend could be added in the boxplot to annotate different colors.

cc @taylordm @chinwallaa @afarrel

**Comment by logstar** [comment]
@taylordm @chinwallaa @afarrel - The database is updated, and I have been developing the API code according to the design in my last comment. The API code may require one or two weeks to develop, which is estimated based on the following complexity analysis.

All explicit parameter combinations are the following Cartesian product, which has 64 combinations.

```
{one EFO ID, all EFO IDs} x
  {zero GTEx tissues, all GTEx tissues} x
  {standard plot width, double plot width} x
  {collapse GTEx tissues, expand GTEx tissues} x
  {primary only, relapse only,
   primary and relapse in the same box,
   primary and relapse in different boxes side by side}
```

API code control flows also need to implicitly handle the following behaviors, according to any explicit parameter combination.

- One EFO ID may match zero or more `Disease`s, aka `cancer_group`s.
- One `Disease` may have one or more `cohort`s, including "All Cohorts".
- One `(Disease, cohort)` tuple may have primary tumor samples, or relapse tumor samples, or both. In all `(Disease, cohort)` tuples of one or all EFO IDs, some may have primary only, some may have relapse only, and some may have both primary and relapse.
- One box represents one `(Disease, cohort, primary/relapse/both)` tuple, and one x-label represents one `(Disease, cohort)` tuple, for `primary and relapse in different boxes side by side`. For other parameter combinations, one box and one x-label both represent one `(Disease, cohort)` tuple, with `primary/relapse` implicitly stated by the parameters.
- If both primary and relapse are required, remove boxes, i.e., `(Disease, cohort, primary/relapse/both)` or `(Disease, cohort)` tuples, that only have primary or relapse.
- If only primary is required, remove relapse samples.
- If only relapse is required, remove primary samples.
- Filter boxes to have >= 3 samples. Some boxes may have primary only, and some boxes may have relapse only, and some boxes both primary and relapse.

I also suggest to start replacing the API with the following workflow, given that the API complexity will further expand after implementing #37 . If we eventually will replace the API, continuously developing the API will keep doubling the effort required to develop final PedOT platform.

- CHOP analytic team generates one long table for each type of plot, e.g. TPM boxplot and DESeq result heatmap. The long table will be sufficient to generate plots that are delivered by the API.
- FNL team loads the long table into PedOT backend database.
- FNL team develops data query API for PedOT frontend to query PedOT database.
- FNL team develops frontend plotting functions using the data query API and a feasible plotting library such as [D3.js](https://d3js.org/).

**Comment by logstar** [comment]
@taylordm @chinwallaa @afarrel - Following are plots with primary-only, relapse-only, primary-and-relapse-in-same-box, and primary-and-relapse-in-different-boxes tumor samples. Primary and/or relapse are described in x-labels with "Specimen = {Pediatric Primary and/or Relapse Tumors}".

I will be working on developing a new systematic testing script to test all possible parameters for a couple of genes and EFO IDs. The current testing shell script, `tests/curl_test_endpoints.sh`, can no longer handle the number of API endpoints and parameters.

Let me know if you have questions or suggestions.

- ![plot3](https://user-images.githubusercontent.com/9595639/140563747-07c486f1-43c7-4e7c-837a-3488cd89b764.png)
- ![plot4](https://user-images.githubusercontent.com/9595639/140563739-cfd6daea-c02d-4a5e-9b29-d3bf63029358.png)
- ![plot1](https://user-images.githubusercontent.com/9595639/140563724-c625bf77-9e7c-40b4-b153-a198be601d7f.png)
- ![plot2](https://user-images.githubusercontent.com/9595639/140563753-da08c7de-401c-4bb7-8f15-4660463289d8.png)

**Comment by logstar** [comment]
@taylordm @chinwallaa @afarrel - I have implemented the testing framework using [R package testthat](https://testthat.r-lib.org/). Unit tests can also be implemented using this testing framework at later point if necessary.

Following are the output of test running. There are 288 API tests in total.

```text
$ ./tests/run_tests.sh 
API base URL: http://localhost:8082
✔ |  OK F W S | Context
✔ | 288       | tests/r_test_scripts/test_endpoint_http.R [587.7 s]                                                                                                                                             

══ Results 
Duration: 587.7 s

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 288 ]
Done running run_tests.sh
```

The response time of each endpoint is summarized in the following boxplot. Both HTTP 200 success and 500 error response codes are both expected. HTTP 200 code means the requested data is available. HTTP 500 code means the requested data is not available, e.g. relapse tumors of Choroid plexus carcinoma. On localhost, JSON table endpoint response times are about 1-2 seconds, and PNG plot endpoint response times are about 2-4 seconds. On remote hosts, the response times will probably be 1-2 seconds slower, but I will test it to confirm.

Given that we expect a plot within 5 seconds, the performance of the R boxplot API may need to be optimized. I will submit an issue about this after testing remote hosts.

![endpoint_response_time_boxplot](https://user-images.githubusercontent.com/9595639/141129904-008dd4f4-fb98-400c-82af-f95555a076cf.png)

**Comment by DBHI-BiG** [comment]
Fantastic work. Thank you for the update.

From: Yuanchao Zhang ***@***.***>
Reply-To: PediatricOpenTargets/OpenPedCan-api ***@***.***>
Date: Wednesday, November 10, 2021 at 9:31 AM
To: PediatricOpenTargets/OpenPedCan-api ***@***.***>
Cc: "Taylor, Deanne M" ***@***.***>, Comment ***@***.***>
Subject: [External]Re: [PediatricOpenTargets/OpenPedCan-api] Update TPM boxplots to show relapse tumors side-by-side with primary tumors (#51)


@taylordm<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftaylordm&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917108340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dYk%2BGk0BLKzgoafOkgQ2pvbhwN%2B37cBpMsBIcVz%2FwAI%3D&reserved=0> @chinwallaa<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchinwallaa&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917118294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=61YMXckQt6ir%2FwIeBdxNAVEMKX7jdczbZxX26R0Hqxo%3D&reserved=0> @afarrel<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fafarrel&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917118294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lrL7lTif0y9dJSXzz92kF%2Fzy%2F6Tn8UPjltjBsEIk%2BQo%3D&reserved=0> - I have implemented the testing framework using R package testthat<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftestthat.r-lib.org%2F&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917128247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f4cusafkfVbbWp%2FOVJ24bqS6k69%2FE%2BKakRe5xI1dBIE%3D&reserved=0>. Unit tests can also be implemented using this testing framework at later point if necessary.

Following are the output of test running. There are 288 API tests in total.

$ ./tests/run_tests.sh



API base URL: http://localhost:8082



✔ |  OK F W S | Context



✔ | 288       | tests/r_test_scripts/test_endpoint_http.R [587.7 s]







══ Results



Duration: 587.7 s







[ FAIL 0 | WARN 0 | SKIP 0 | PASS 288 ]



Done running run_tests.sh



The response time of each endpoint is summarized in the following boxplot. Both HTTP 200 success and 500 error response codes are both expected. HTTP 200 code means the requested data is available. HTTP 500 code means the requested data is not available, e.g. relapse tumors of Choroid plexus carcinoma. On localhost, JSON table endpoint response times are about 1-2 seconds, and PNG plot endpoint response times are about 2-4 seconds. On remote hosts, the response times will probably be 1-2 seconds slower, but I will test it to confirm.

Given that we expect a plot within 5 seconds, the performance of the R boxplot API may need to be optimized. I will submit an issue about this after testing remote hosts.

[endpoint_response_time_boxplot]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F9595639%2F141129904-008dd4f4-fb98-400c-82af-f95555a076cf.png&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917128247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3qA0tSW0%2FXwR0w2GrxosRM%2ByBKt7m%2FaqSjskP5DPNYo%3D&reserved=0>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPediatricOpenTargets%2FOpenPedCan-api%2Fissues%2F51%23issuecomment-965275705&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917138202%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8igDCvTUewBGHu1aeNAlUoxNP%2FGbJJo8P9y5tsXGtRg%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABG2W5YMLNGTMKFZSGL3GR3ULJ64BANCNFSM5F52EHFQ&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917138202%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YnZtcz1Iargic3sJ6oETWbYR%2FqwKblv9DfgLWAFBJXM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917148159%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eBuIO6zG8FlrDR2RrF3xlEYz2GFYaizrfdyBZN1iFMM%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CTAYLORDM%40chop.edu%7C7c1b8bef74384015a2bc08d9a456c924%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637721514917158124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zso5X3EgtcwSk2UWVnk%2BCSNJ%2BnOxeF724yuRa7PjaL0%3D&reserved=0>.
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.
